-- Seed generato dai dati statici esistenti (public/data/*.json e src/locales/*.json)
-- Esegui dopo schema.sql per popolare le tabelle con i contenuti attuali del sito.

-- PROJECTS
insert into public.projects (lang, title, technology, description, images, github_url, site_url, sort_order)
values
  ('en', 'DiscreetTab', 'Chrome Extension', 'Development of a lightweight privacy-focused Chrome extension that lets users hide tab titles and favicons. It offers customizable title formats, per-domain presets synced through Chrome Sync, a temporary discreet mode, and a keyboard shortcut for quick toggling. Everything runs locally with no data collection.', '{"/DiscreetTab1.png","/DiscreetTab2.png"}', 'https://github.com/TobiaRigon/DiscreetTab', 'https://discreettab.tobiarigon.com/', 0),
  ('en', 'Kubix Link – NAV 365 Sync', 'PHP Integration Project', 'Development of a bidirectional synchronization system between Lectra Kubix Link (PLM) and Microsoft NAV 365 (ERP), using PHP, REST APIs, and webhooks. The project involved handling data consistency and real-time updates across both platforms. I was responsible for back-end development and system integration, ensuring robust communication between the two environments. This work significantly improved internal workflows and data accuracy.', '{"/Sync1.png","/Sync2.png"}', null, null, 1),
  ('en', 'Spotify Auto Playlist', 'Python Automation Project', 'Development of a Python script that automates the creation and updating of a Spotify playlist using the Spotify Web API and the Spotipy library. The project involves authenticating with Spotify''s API, managing user credentials securely, and programmatically adding predefined tracks to a playlist. This automation enhances user experience by streamlining playlist management.', '{"/Spotify1.png","/Spotify2.png"}', 'https://github.com/TobiaRigon/Spotify_Auto_Playlist', null, 2),
  ('en', 'My Portfolio', 'Showcasing My Passion and Skills', 'This portfolio is built with Vue.js and Three.js. Clean structure, practical choices, no unnecessary complexity. The 3D background runs on Three.js and GSAP, content is bilingual via vue-i18n, and the site is deployed on Vercel.', '{"/Portfolio1.png","/Portfolio2.png","/Portfolio3.png"}', 'https://github.com/TobiaRigon/vue-portfolio', null, 3),
  ('it', 'DiscreetTab', 'Estensione Chrome', 'Sviluppo di un''estensione Chrome leggera incentrata sulla privacy, che consente agli utenti di nascondere titoli e favicon delle schede. Include formati di titolo personalizzabili, memoria per dominio con sincronizzazione tramite Chrome Sync, modalità discreta temporanea e scorciatoia da tastiera per un''attivazione rapida. Tutte le funzionalità sono locali, senza raccolta di dati.', '{"/DiscreetTab1.png","/DiscreetTab2.png"}', 'https://github.com/TobiaRigon/DiscreetTab', 'https://discreettab.tobiarigon.com/', 0),
  ('it', 'Kubix Link – NAV 365 Sync', 'Progetto di Integrazione PHP', 'Sviluppo di un sistema di sincronizzazione bidirezionale tra Lectra Kubix Link (PLM) e Microsoft NAV 365 (ERP), utilizzando PHP, REST API e webhook. Il progetto ha comportato la gestione della coerenza dei dati e degli aggiornamenti in tempo reale tra entrambe le piattaforme. Mi sono occupato dello sviluppo back-end e dell''integrazione tra sistemi, garantendo una comunicazione robusta tra gli ambienti. Questo lavoro ha migliorato significativamente i flussi interni e l''accuratezza dei dati.', '{"/Sync1.png","/Sync2.png"}', null, null, 1),
  ('it', 'Spotify Auto Playlist', 'Progetto di Automazione in Python', 'Sviluppo di uno script in Python che automatizza la creazione e l''aggiornamento di una playlist Spotify usando le API Web di Spotify e la libreria Spotipy. Il progetto include l''autenticazione con le API di Spotify, la gestione sicura delle credenziali utente e l''aggiunta programmata di brani a una playlist. Questa automazione migliora l''esperienza dell''utente semplificando la gestione delle playlist.', '{"/Spotify1.png","/Spotify2.png"}', 'https://github.com/TobiaRigon/Spotify_Auto_Playlist', null, 2),
  ('it', 'Il Mio Portfolio', 'Vetrina delle mie Competenze e Passioni', 'Questo portfolio è costruito con Vue.js e Three.js. Struttura pulita, scelte pratiche, nessuna complessità superflua. Lo sfondo 3D è gestito con Three.js e GSAP, i contenuti sono bilingue tramite vue-i18n e il sito è distribuito su Vercel.', '{"/Portfolio1.png","/Portfolio2.png","/Portfolio3.png"}', 'https://github.com/TobiaRigon/vue-portfolio', null, 3);

-- TEXTS
insert into public.texts (key, lang, content)
values
  ('home.name', 'en', '"Tobia Rigon"'::jsonb),
  ('home.role', 'en', '"Web Developer & IT Specialist"'::jsonb),
  ('home.section0.title', 'en', '"From 3D to real-world systems."'::jsonb),
  ('home.section0.body', 'en', '"I started my journey in CGI and 3D, developing a strong visual and problem-solving mindset. Over the years I transitioned into web development and later into IT support and systems integration. Today I work in a structured manufacturing environment, dealing with internal tools, automation, troubleshooting and business-critical workflows."'::jsonb),
  ('home.section1.title', 'en', '"Systems, integrations and AI."'::jsonb),
  ('home.section1.body', 'en', '"Over the last few years I''ve worked on ERP/PLM integrations, APIs, scripting, Linux environments, automation and AI-assisted workflows. I''m particularly interested in the practical integration of AI into production and operational processes, with a focus on efficiency, reliability, security and system control."'::jsonb),
  ('home.section2', 'en', '"Building useful systems."'::jsonb),
  ('about.greeting', 'en', '"Hi, I''m Tobia."'::jsonb),
  ('about.bio', 'en', '["I work as a Web Developer and IT Specialist in an enterprise manufacturing company within the luxury fashion industry. My work focuses on internal development, systems integration, IT support and operational process automation.","Over the last few years I''ve worked on ERP and PLM integrations, APIs, scripting, Linux environments, infrastructure troubleshooting and business-critical tools used daily in production.","I work daily across Windows and Linux environments, supporting infrastructure, users and operational systems in complex production contexts.","My background started in CGI and 3D, an experience that still influences how I approach design, logic and problem solving.","Today my focus is building reliable systems, automating real-world workflows and integrating AI tools in a pragmatic and sustainable way."]'::jsonb),
  ('about.aiTitle', 'en', '"AI as a tool, not a shortcut."'::jsonb),
  ('about.aiBody', 'en', '["I closely follow the evolution of AI and actively integrate it into my workflows in practical ways. I use AI tools for development, automation, research and operational support, while maintaining strong attention to validation, security and system understanding.","I believe the real value isn''t in using AI blindly, but in knowing when to use it, how to validate its output and how to integrate it into real workflows without creating unnecessary dependencies."]'::jsonb),
  ('about.likesTitle', 'en', '"What I Like"'::jsonb),
  ('about.learningTitle', 'en', '"What I''m Learning"'::jsonb),
  ('work.cta', 'en', '"Projects, systems and tools built for real-world environments."'::jsonb),
  ('work.intro', 'en', '"A mix of professional work and personal projects. Some were built on the job to solve real operational problems, others out of curiosity or to automate something that was wasting my time."'::jsonb),
  ('work.prev', 'en', '"Previous"'::jsonb),
  ('work.next', 'en', '"Next"'::jsonb),
  ('notFound.sets', 'en', '[{"title":"Impressive.","message":"You clicked yourself straight into nowhere. Nice one.","button":"Try again, smarter this time"},{"title":"Well, well, well...","message":"Look who wandered in. A young explorer!","button":"Back before you get more lost"},{"title":"Nice","message":"You''ve officially reached the middle of nowhere. Proud of you.","button":"Let''s pretend this didn''t happen"}]'::jsonb),
  ('home.name', 'it', '"Tobia Rigon"'::jsonb),
  ('home.role', 'it', '"Web Developer & IT Specialist"'::jsonb),
  ('home.section0.title', 'it', '"Dal 3D ai sistemi reali."'::jsonb),
  ('home.section0.body', 'it', '"Ho iniziato il mio percorso nel mondo della CGI e del 3D, sviluppando un forte approccio visivo e orientato al problem solving. Negli anni mi sono spostato verso lo sviluppo web e successivamente verso il supporto IT e l''integrazione di sistemi. Oggi lavoro in una realtà manifatturiera strutturata, occupandomi di strumenti interni, automazioni, troubleshooting e flussi aziendali critici."'::jsonb),
  ('home.section1.title', 'it', '"Sistemi, integrazioni e AI."'::jsonb),
  ('home.section1.body', 'it', '"Negli ultimi anni ho lavorato su integrazioni ERP/PLM, API, scripting, ambienti Linux, automazioni e workflow basati sull''intelligenza artificiale. Mi interessa soprattutto l''integrazione pratica dell''AI nei processi produttivi e operativi, con un approccio orientato all''efficienza ma attento ad affidabilità, sicurezza e controllo dei sistemi."'::jsonb),
  ('home.section2', 'it', '"Costruire sistemi utili."'::jsonb),
  ('about.greeting', 'it', '"Ciao, sono Tobia."'::jsonb),
  ('about.bio', 'it', '["Lavoro come Web Developer e IT Specialist in un''azienda manifatturiera enterprise nel settore della moda di lusso. Mi occupo di sviluppo interno, integrazione di sistemi, supporto IT e automazione di processi operativi.","Negli ultimi anni ho lavorato su integrazioni tra ERP e PLM, API, scripting, ambienti Linux, troubleshooting infrastrutturale e strumenti business-critical utilizzati quotidianamente in produzione.","Lavoro quotidianamente tra ambienti Windows e Linux, supportando infrastrutture, utenti e sistemi operativi in contesti produttivi complessi.","Il mio percorso è iniziato nel mondo della CGI e del 3D, esperienza che continua a influenzare il mio approccio al design, alla logica e alla risoluzione dei problemi.","Oggi il mio focus è costruire sistemi affidabili, automatizzare workflow reali e integrare strumenti AI in modo pragmatico e sostenibile."]'::jsonb),
  ('about.aiTitle', 'it', '"AI come strumento, non scorciatoia."'::jsonb),
  ('about.aiBody', 'it', '["Seguo da vicino l''evoluzione dell''intelligenza artificiale e cerco di integrarla nei miei workflow in modo concreto. Utilizzo strumenti AI per sviluppo, automazione, ricerca e supporto operativo, mantenendo sempre attenzione a validazione, sicurezza e comprensione dei sistemi.","Credo che il valore non stia nell''usare l''AI ciecamente, ma nel sapere quando usarla, come verificarne l''output e come integrarla in processi reali senza creare dipendenze inutili."]'::jsonb),
  ('about.likesTitle', 'it', '"What I Like"'::jsonb),
  ('about.learningTitle', 'it', '"What I''m Learning"'::jsonb),
  ('work.cta', 'it', '"Progetti, sistemi e strumenti costruiti per ambienti reali."'::jsonb),
  ('work.intro', 'it', '"Un mix di lavoro professionale e progetti personali. Alcuni realizzati in ambito lavorativo per risolvere problemi operativi reali, altri per curiosità o per automatizzare qualcosa che mi stava facendo perdere tempo."'::jsonb),
  ('work.prev', 'it', '"Precedente"'::jsonb),
  ('work.next', 'it', '"Successivo"'::jsonb),
  ('notFound.sets', 'it', '[{"title":"Notevole.","message":"Hai cliccato dritto nel nulla. Complimenti vivissimi.","button":"Riprova, magari con più impegno"},{"title":"Guarda chi c''è...","message":"Un giovane esploratore! E senza mappa, a quanto pare.","button":"Torna indietro finché sei in tempo"},{"title":"Grande!","message":"Hai ufficialmente raggiunto il centro del nulla. Bravo davvero.","button":"Facciamo finta che non sia mai successo"}]'::jsonb)
on conflict (key, lang) do update set content = excluded.content, updated_at = now();
